### ISSUE TITLE
does PBD support dwarf2 binaries generated by clang? 

### ISSUE THREAD

**Issue by mlite** [Theldus/PBD#11] opened 2020-07-07 01:21 UTC
It seems PBD works for binaries generated by gcc with glibc, but not for the ones linked with other libc.

**Comment by Theldus** [comment] 2020-07-07 01:47
PBD works well for GCC and Clang, so much so that the last commit (ca9f5e5baf5475eebb7799ec77684dff3758a6a2) was successfully built for 32/64 bits for GCC and Clang on Travis CI, just check here: https://github.com/Theldus/PBD/runs/824133220

However, it should be taken into account if the GCC/Clang for your distro builds "PIE" executables by default or not. Since the PBD does not support it, you also need to specify the flag '-no-pie' (while building the executable) if this is the case. The build scripts for automated tests and benchmarks do this check, please check the `src/tests/Makefile` and `src/benchs/Makefile` files for some insights.

**Comment by mlite** [comment] 2020-07-07 02:39
Does it work with musl (1.1.10)?

**Comment by Theldus** [comment] 2020-07-07 02:50
> Does it work with musl (1.1.10)?

Also works fine, GCC v5.3 + musl v1.1.10. What kind of issues you're facing? it's hard to help
without any further information... what is your system environment?:
- GCC/Clang version
- Distro version
- etc

in summary: what do I have to do to have the same behavior you are getting?

**Comment by mlite** [comment] 2020-07-07 03:02
I use docker image: i386/alpine:3.5, and clang-3.8 to build the tested binaries.  I can run pbd with the binaries, but pbd cannot intercept the value changes.  If I build the same code with clang-3.8 on debian, everything works.

**Comment by Theldus** [comment] 2020-07-07 03:19
@mlite Could you double check if your binaries are _not_ PIE executables? you can check that with: `file a.out`. A example of desired output would be something like:

```
a.out: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked,
interpreter /lib/ld-musl-x86_64.so.1, not stripped
```
a _not_ desirable output would be:
```
a.out: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked,
interpreter /lib/ld-musl-x86_64.so.1, not stripped
```
`LSB shared object` and `LSB pie executable` means the same thing: "PIE" executable, and it's not supported by PBD. In that case, you *must* build your debugged program with an additional flag: `-no-pie`.

That's the only thing that I could think of.

**Comment by mlite** [comment] 2020-07-07 06:10
I can make it work by building it with static link.  Here is another problem:
1. if a binary has this file permission:
   755 a.out
   and the owner is root
2. if I run pbd as a different UID, I got segfault.  Does PBD need the write permission?

**Comment by Theldus** [comment] 2020-07-07 07:43
> Does PBD need the write permission? why?

Nope, and this does not make any sense. What PBD needs for sure is read _and_ execute permissions, so, 755 or 555 will work just fine, whether root or not, please make sure of that. For instance, your IDE is setting a.out as 311, which is very weird (and explains as why I am not able to run).

You said that you're facing issues inside Docker, right? If I recall correctly, Docker disables some syscalls and kernel features by default, like `ptrace()`, so maybe you have to enable it first, doing something like [this](https://stackoverflow.com/a/42030182/3594716) or [this](https://github.com/moby/moby/issues/21051#issuecomment-325036902). But before doing it, make sure that your Docker is _not_ able to run something that uses ptrace(), like strace or even GDB.

Lastly, what is the stack trace for that segfault? what is the offending function?

**Comment by mlite** [comment] 2020-07-07 17:07
It's a file permission thing. I change the permission of a.out to 777, then I can use pbd with the code as a different user.

**Comment by mlite** [comment] 2020-07-07 17:42
Can you find out why it needs write permission?  I cannot allow the binaries be writable for security reason.

**Comment by Theldus** [comment] 2020-07-07 18:22
Are you sure about that? I mean, PBD at no time performs writing in binary, nor does libdwarf and libsparse do. 

I tried to reproduce it here, but I managed to run normally with permissions like "555".

**Comment by mlite** [comment] 2020-07-08 02:58
I cannot find the reason of segfault because the stack trace is not readable.  Yes, I ran it in a container, some unknown facts + file permission causes segfault.

**Comment by Theldus** [comment] 2021-09-18 04:44
More than a year has passed since the last message, so I will close the issue.

Feel free to reopen it (or create a new one) if you want to revisit the issue and/or have new PBD questions.

**Closed by Theldus** 2021-09-18 04:44 UTC
Labels: question
